### ISSUE TITLE
using joins instead of subselects

### ISSUE THREAD

**Issue by AgustiLumbreras** [mattiasgeniar/zabbix-orphaned-data-cleanup#10]
Hi,

is faster to use join that the subselect
for example

subselect -> DELETE FROM alerts WHERE NOT actionid IN (SELECT actionid FROM actions);
left join -> DELETE alerts FROM alerts lefft join actions ON alerts.actionid = actions.actionid WHERE actions.actionid ;

**Comment by mattiasgeniar** [comment]
Hi!

I think you're right, but at the moment performance isn't an issue for me. Feel free to send a PR that fixes those queries, but right now functionality is 'good enough'.

If you don't mind, I'll close this issue, but I'll accept any PR that fixes those queries. :-)

Take care,

Mattias
