### ISSUE TITLE
password on the command line

### ISSUE THREAD

**Issue by osemych** [mattiasgeniar/zabbix-orphaned-data-cleanup#8]
I would add stderr redirection to /dev/null in shell scripts as script output gets polluted with warning "Using a password on the command line interface can be insecure."
Another and more secure approach is to add configuration file with credentials and specify it with `--defaults-extra-file` parameter.

**Comment by Nefelim4ag** [comment]
I'll fix that when i write some helper for parallelization on big tables (history/trends).

**Comment by mattiasgeniar** [comment]
This has been resolved with @Nefelim4ag 's PR #9.
